#ifndef FLOCKCONFIG_H_
#define FLOCKCONFIG_H_

// Video configuration
#define SCREEN_WIDTH    1280
#define SCREEN_HEIGHT   720
#define SCREEN_DEPTH    32

#define FPS 0

// BOID parameters
#define NUM_BOIDS 1500

#define MAX_BOID_VELOCITY 10
#define MIN_BOID_SEPARATION 10
#define MIN_BOID_SEPARATION_SQUARED (MIN_BOID_SEPARATION * MIN_BOID_SEPARATION)
#define MAX_BOID_STEERING_FORCE 0.2
#define NEIGHBORHOOD_RADIUS 50
#define NEIGHBORHOOD_RADIUS_SQUARED (NEIGHBORHOOD_RADIUS * NEIGHBORHOOD_RADIUS)
#endif
